2025-03-20 22:22:00,697 - main - INFO - 创建数据库表...
2025-03-20 22:22:00,912 - main - INFO - 数据库表创建完成
2025-03-20 22:22:00,912 - main - INFO - 注册路由...
2025-03-20 22:24:12,724 - main - INFO - 创建数据库表...
2025-03-20 22:24:12,957 - main - INFO - 数据库表创建完成
2025-03-20 22:24:12,957 - main - INFO - 注册路由...
2025-03-20 22:32:52,382 - main - INFO - 创建数据库表...
2025-03-20 22:32:52,591 - main - INFO - 数据库表创建完成
2025-03-20 22:32:52,592 - main - INFO - 注册路由...
2025-03-20 22:32:52,846 - main - INFO - 路由注册完成
2025-03-20 22:46:09,139 - main - INFO - 创建数据库表...
2025-03-20 22:46:09,348 - main - INFO - 数据库表创建完成
2025-03-20 22:46:09,349 - main - INFO - 注册路由...
2025-03-20 22:48:18,704 - main - INFO - 创建数据库表...
2025-03-20 22:48:18,926 - main - INFO - 数据库表创建完成
2025-03-20 22:48:18,927 - main - INFO - 注册路由...
2025-03-20 22:48:19,176 - main - INFO - 路由注册完成
2025-03-20 22:54:30,603 - main - INFO - 创建数据库表...
2025-03-20 22:54:30,883 - main - INFO - 数据库表创建完成
2025-03-20 22:54:30,883 - main - INFO - 注册路由...
2025-03-20 22:54:31,146 - main - INFO - 路由注册完成
2025-03-21 18:46:48,229 - main - INFO - 创建数据库表...
2025-03-21 18:46:48,419 - main - INFO - 数据库表创建完成
2025-03-21 18:46:48,419 - main - INFO - 注册路由...
2025-03-21 18:46:48,622 - main - INFO - 路由注册完成
2025-03-21 19:58:52,347 - main - INFO - 创建数据库表...
2025-03-21 19:58:52,569 - main - INFO - 数据库表创建完成
2025-03-21 19:58:52,570 - main - INFO - 注册路由...
2025-03-21 19:58:52,797 - main - INFO - 路由注册完成
2025-03-21 20:02:36,134 - main - INFO - 创建数据库表...
2025-03-21 20:02:36,329 - main - INFO - 数据库表创建完成
2025-03-21 20:02:36,329 - main - INFO - 注册路由...
2025-03-21 20:02:36,535 - main - INFO - 路由注册完成
2025-03-21 20:54:10,247 - main - INFO - 创建数据库表...
2025-03-21 20:54:10,443 - main - INFO - 数据库表创建完成
2025-03-21 20:54:10,443 - main - INFO - 注册路由...
2025-03-21 20:54:10,656 - main - INFO - 路由注册完成
2025-03-21 21:31:09,215 - main - INFO - 创建数据库表...
2025-03-21 21:31:09,461 - main - INFO - 数据库表创建完成
2025-03-21 21:31:09,462 - main - INFO - 注册路由...
2025-03-21 21:31:09,737 - main - INFO - 路由注册完成
2025-03-21 22:00:52,323 - main - INFO - 创建数据库表...
2025-03-21 22:00:52,512 - main - INFO - 数据库表创建完成
2025-03-21 22:00:52,513 - main - INFO - 注册路由...
2025-03-21 22:00:52,715 - main - INFO - 路由注册完成
2025-03-21 22:24:28,384 - main - INFO - 创建数据库表...
2025-03-21 22:24:28,648 - main - INFO - 数据库表创建完成
2025-03-21 22:24:28,649 - main - INFO - 注册路由...
2025-03-21 22:24:28,933 - main - INFO - 路由注册完成
2025-03-21 22:35:09,451 - main - INFO - 创建数据库表...
2025-03-21 22:35:09,649 - main - INFO - 数据库表创建完成
2025-03-21 22:35:09,649 - main - INFO - 注册路由...
2025-03-21 22:35:09,933 - main - INFO - 路由注册完成
2025-04-03 22:32:56,723 - main - INFO - 创建数据库表...
2025-04-03 22:32:57,020 - main - INFO - 数据库表创建完成
2025-04-03 22:32:57,020 - main - INFO - 注册路由...
2025-04-03 22:32:57,350 - main - INFO - 路由注册完成
2025-04-03 22:32:57,491 - main - INFO - 创建数据库表...
2025-04-03 22:32:57,704 - main - INFO - 数据库表创建完成
2025-04-03 22:32:57,704 - main - INFO - 注册路由...
2025-04-03 22:32:57,919 - main - INFO - 路由注册完成
2025-04-03 22:34:48,636 - main - INFO - 创建数据库表...
2025-04-03 22:34:48,867 - main - INFO - 数据库表创建完成
2025-04-03 22:34:48,867 - main - INFO - 注册路由...
2025-04-03 22:34:49,079 - main - INFO - 路由注册完成
2025-04-03 22:35:16,328 - main - INFO - 创建数据库表...
2025-04-03 22:35:16,542 - main - INFO - 数据库表创建完成
2025-04-03 22:35:16,542 - main - INFO - 注册路由...
2025-04-03 22:35:16,743 - main - INFO - 路由注册完成
2025-04-03 22:35:33,553 - main - INFO - 创建数据库表...
2025-04-03 22:35:33,747 - main - INFO - 数据库表创建完成
2025-04-03 22:35:33,748 - main - INFO - 注册路由...
2025-04-03 22:35:33,922 - main - INFO - 路由注册完成
2025-04-03 22:35:44,929 - main - INFO - 创建数据库表...
2025-04-03 22:35:45,120 - main - INFO - 数据库表创建完成
2025-04-03 22:35:45,121 - main - INFO - 注册路由...
2025-04-03 22:35:45,291 - main - INFO - 路由注册完成
2025-04-03 22:35:52,197 - inventory_api - INFO - 获取所有货架
2025-04-03 22:35:52,227 - inventory_api - INFO - 找到 2 个货架
2025-04-03 22:35:53,309 - inventory_api - INFO - 获取货架 1 的所有货位
2025-04-03 22:35:53,317 - inventory_api - INFO - 找到 4 个货位
2025-04-03 22:36:19,430 - inventory_api - INFO - 获取货架 1 的所有货位
2025-04-03 22:36:19,435 - inventory_api - INFO - 找到 4 个货位
2025-04-03 22:36:26,004 - inventory_api - INFO - 获取货架 2 的所有货位
2025-04-03 22:36:26,008 - inventory_api - INFO - 找到 4 个货位
2025-04-03 22:39:16,875 - employee_api - INFO - 验证订单 ID: 10
2025-04-03 22:39:16,876 - employee_api - INFO - 订单 10 验证成功，重定向到订单详情页
2025-04-04 17:15:24,514 - main - INFO - 创建数据库表...
2025-04-04 17:15:24,762 - main - INFO - 数据库表创建完成
2025-04-04 17:15:24,762 - main - INFO - 注册路由...
2025-04-04 17:47:26,914 - main - INFO - 创建数据库表...
2025-04-04 17:47:27,125 - main - INFO - 数据库表创建完成
2025-04-04 17:47:27,125 - main - INFO - 注册路由...
2025-04-04 17:47:27,313 - main - INFO - 路由注册完成
2025-04-04 18:10:27,742 - employee_api - INFO - 标记订单 11 的商品 10 为已取货，库存ID: 2, 数量: 3
2025-04-04 18:10:27,758 - employee_api - INFO - 成功标记订单 11 的商品 10 为已取货
2025-04-04 18:10:40,805 - employee_api - INFO - 标记订单 11 为已完成
2025-04-04 18:10:40,813 - employee_api - INFO - 订单 11 已标记为完成
2025-04-04 18:40:33,586 - main - INFO - 创建数据库表...
2025-04-04 18:40:33,784 - main - INFO - 数据库表创建完成
2025-04-04 18:40:33,784 - main - INFO - 注册路由...
2025-04-04 18:44:19,139 - main - INFO - 创建数据库表...
2025-04-04 18:44:19,337 - main - INFO - 数据库表创建完成
2025-04-04 18:44:19,338 - main - INFO - 注册路由...
2025-04-04 18:59:45,379 - main - INFO - 创建数据库表...
2025-04-04 18:59:45,590 - main - INFO - 数据库表创建完成
2025-04-04 18:59:45,592 - main - INFO - 注册路由...
2025-04-04 18:59:59,438 - main - INFO - 创建数据库表...
2025-04-04 18:59:59,662 - main - INFO - 数据库表创建完成
2025-04-04 18:59:59,662 - main - INFO - 注册路由...
2025-04-04 19:00:32,731 - main - INFO - 创建数据库表...
2025-04-04 19:00:32,936 - main - INFO - 数据库表创建完成
2025-04-04 19:00:32,936 - main - INFO - 注册路由...
2025-04-04 19:01:53,664 - main - INFO - 创建数据库表...
2025-04-04 19:01:53,868 - main - INFO - 数据库表创建完成
2025-04-04 19:01:53,869 - main - INFO - 注册路由...
2025-04-04 19:06:17,993 - main - INFO - 创建数据库表...
2025-04-04 19:06:18,197 - main - INFO - 数据库表创建完成
2025-04-04 19:06:18,199 - main - INFO - 注册路由...
2025-04-04 19:10:11,608 - main - INFO - 创建数据库表...
2025-04-04 19:10:11,807 - main - INFO - 数据库表创建完成
2025-04-04 19:10:11,808 - main - INFO - 注册路由...
2025-04-04 19:10:11,983 - main - INFO - 路由注册完成
2025-04-04 19:12:03,370 - employee_api - INFO - 标记订单 12 的商品 11 为已取货，库存ID: 2, 数量: 3
2025-04-04 19:12:03,387 - employee_api - INFO - 成功标记订单 12 的商品 11 为已取货
2025-04-04 19:12:15,260 - employee_api - INFO - 标记订单 12 为已完成
2025-04-04 19:12:15,267 - employee_api - INFO - 订单 12 已标记为完成
2025-04-04 21:33:58,132 - main - INFO - 创建数据库表...
2025-04-04 21:33:58,337 - main - INFO - 数据库表创建完成
2025-04-04 21:33:58,337 - main - INFO - 注册路由...
2025-04-04 21:33:58,517 - main - INFO - 路由注册完成
2025-04-04 21:34:13,587 - main - INFO - 创建数据库表...
2025-04-04 21:34:13,783 - main - INFO - 数据库表创建完成
2025-04-04 21:34:13,784 - main - INFO - 注册路由...
2025-04-04 21:34:13,963 - main - INFO - 路由注册完成
2025-04-04 21:39:42,108 - employee_api - INFO - 上传订单 13 的照片
2025-04-04 21:39:42,121 - employee_api - INFO - 订单 13 照片上传成功，URL: /static/uploads/order_photos/order_13_20250404213942.jpg
2025-04-04 21:39:49,494 - employee_api - INFO - 标记订单 13 为已完成
2025-04-04 21:39:49,502 - employee_api - INFO - 订单 13 已标记为完成
2025-04-04 21:40:45,246 - main - ERROR - URL: http://8.133.194.133:8000/client/order/13, Method: GET, Error: 'starlette.requests.Request object' has no attribute 'db', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/client.py", line 149, in client_order_detail
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/client/order_detail.html", line 208, in <module>
    {% for photo in request.db.query(request.models.OrderPhoto).filter(request.models.OrderPhoto.order_id == order.id).all() %}
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'starlette.requests.Request object' has no attribute 'db'

2025-04-04 21:58:34,035 - main - INFO - 创建数据库表...
2025-04-04 21:58:34,236 - main - INFO - 数据库表创建完成
2025-04-04 21:58:34,236 - main - INFO - 注册路由...
2025-04-04 21:58:34,404 - main - INFO - 路由注册完成
2025-04-05 02:57:29,096 - main - INFO - 创建数据库表...
2025-04-05 02:57:29,328 - main - INFO - 数据库表创建完成
2025-04-05 02:57:29,329 - main - INFO - 注册路由...
2025-04-05 02:57:29,546 - main - INFO - 路由注册完成
2025-04-05 02:58:03,699 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:07:13,617 - main - INFO - 创建数据库表...
2025-04-05 03:07:13,858 - main - INFO - 数据库表创建完成
2025-04-05 03:07:13,858 - main - INFO - 注册路由...
2025-04-05 03:07:14,123 - main - INFO - 路由注册完成
2025-04-05 03:08:12,874 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:10:21,050 - main - INFO - 创建数据库表...
2025-04-05 03:10:21,246 - main - INFO - 数据库表创建完成
2025-04-05 03:10:21,246 - main - INFO - 注册路由...
2025-04-05 03:10:21,458 - main - INFO - 路由注册完成
2025-04-05 03:10:28,835 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:10:33,166 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:10:52,632 - main - INFO - 创建数据库表...
2025-04-05 03:10:52,827 - main - INFO - 数据库表创建完成
2025-04-05 03:10:52,828 - main - INFO - 注册路由...
2025-04-05 03:10:53,043 - main - INFO - 路由注册完成
2025-04-05 03:11:07,327 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:14:42,815 - main - INFO - 创建数据库表...
2025-04-05 03:14:43,023 - main - INFO - 数据库表创建完成
2025-04-05 03:14:43,024 - main - INFO - 注册路由...
2025-04-05 03:14:43,248 - main - INFO - 路由注册完成
2025-04-05 03:15:12,529 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:15:25,743 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:23:09,501 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:23:13,059 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:23:41,421 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:31:22,611 - main - INFO - 创建数据库表...
2025-04-05 03:31:23,040 - main - INFO - 数据库表创建完成
2025-04-05 03:31:23,041 - main - INFO - 注册路由...
2025-04-05 03:31:23,268 - main - INFO - 路由注册完成
2025-04-05 03:32:13,158 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:32:16,888 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:38:52,889 - main - INFO - 创建数据库表...
2025-04-05 03:38:53,097 - main - INFO - 数据库表创建完成
2025-04-05 03:38:53,097 - main - INFO - 注册路由...
2025-04-05 03:38:53,321 - main - INFO - 路由注册完成
2025-04-05 03:40:22,998 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:44:13,395 - main - INFO - 创建数据库表...
2025-04-05 03:44:13,662 - main - INFO - 数据库表创建完成
2025-04-05 03:44:13,663 - main - INFO - 注册路由...
2025-04-05 03:44:13,959 - main - INFO - 路由注册完成
2025-04-05 03:44:21,640 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:46:05,653 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:49:30,504 - main - INFO - 创建数据库表...
2025-04-05 03:49:30,699 - main - INFO - 数据库表创建完成
2025-04-05 03:49:30,699 - main - INFO - 注册路由...
2025-04-05 03:49:30,908 - main - INFO - 路由注册完成
2025-04-05 03:49:46,889 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:56:01,344 - main - INFO - 创建数据库表...
2025-04-05 03:56:01,780 - main - INFO - 数据库表创建完成
2025-04-05 03:56:01,781 - main - INFO - 注册路由...
2025-04-05 03:56:02,027 - main - INFO - 路由注册完成
2025-04-05 03:56:12,676 - main - ERROR - URL: http://8.133.194.133:8000/admin/inventory, Method: GET, Error: 'app.db.models.Product object' has no attribute 'stock_threshold', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 442, in admin_inventory
    return templates.TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mlsp/app/templates/admin/inventory.html", line 224, in <module>
    {% if product.stock <= product.stock_threshold %}
jinja2.exceptions.UndefinedError: 'app.db.models.Product object' has no attribute 'stock_threshold'

2025-04-05 03:57:54,183 - main - INFO - 创建数据库表...
2025-04-05 03:57:54,380 - main - INFO - 数据库表创建完成
2025-04-05 03:57:54,380 - main - INFO - 注册路由...
2025-04-05 03:57:54,598 - main - INFO - 路由注册完成
2025-04-05 03:58:30,948 - main - INFO - 创建数据库表...
2025-04-05 03:58:31,326 - main - INFO - 数据库表创建完成
2025-04-05 03:58:31,327 - main - INFO - 注册路由...
2025-04-05 03:58:31,575 - main - INFO - 路由注册完成
2025-04-05 04:15:57,758 - main - INFO - 创建数据库表...
2025-04-05 04:15:57,983 - main - INFO - 数据库表创建完成
2025-04-05 04:15:57,984 - main - INFO - 注册路由...
2025-04-05 04:15:58,201 - main - INFO - 路由注册完成
2025-04-05 04:30:18,377 - main - INFO - 创建数据库表...
2025-04-05 04:30:18,608 - main - INFO - 数据库表创建完成
2025-04-05 04:30:18,608 - main - INFO - 注册路由...
2025-04-05 04:30:18,831 - main - INFO - 路由注册完成
2025-04-05 04:36:10,397 - main - INFO - 创建数据库表...
2025-04-05 04:36:10,593 - main - INFO - 数据库表创建完成
2025-04-05 04:36:10,594 - main - INFO - 注册路由...
2025-04-05 04:36:10,810 - main - INFO - 路由注册完成
2025-04-05 04:42:17,678 - main - INFO - 创建数据库表...
2025-04-05 04:42:17,874 - main - INFO - 数据库表创建完成
2025-04-05 04:42:17,875 - main - INFO - 注册路由...
2025-04-05 04:42:18,089 - main - INFO - 路由注册完成
2025-04-05 04:52:47,346 - main - INFO - 创建数据库表...
2025-04-05 04:52:47,559 - main - INFO - 数据库表创建完成
2025-04-05 04:52:47,560 - main - INFO - 注册路由...
2025-04-05 04:52:47,784 - main - INFO - 路由注册完成
2025-04-05 05:08:29,598 - main - INFO - 创建数据库表...
2025-04-05 05:08:29,801 - main - INFO - 数据库表创建完成
2025-04-05 05:08:29,803 - main - INFO - 注册路由...
2025-04-05 05:08:30,035 - main - INFO - 路由注册完成
2025-04-05 05:13:08,579 - main - INFO - 创建数据库表...
2025-04-05 05:13:08,798 - main - INFO - 数据库表创建完成
2025-04-05 05:13:08,799 - main - INFO - 注册路由...
2025-04-05 05:13:09,062 - main - INFO - 路由注册完成
2025-04-05 05:20:13,019 - main - INFO - 创建数据库表...
2025-04-05 05:20:13,215 - main - INFO - 数据库表创建完成
2025-04-05 05:20:13,216 - main - INFO - 注册路由...
2025-04-05 05:20:13,429 - main - INFO - 路由注册完成
2025-04-05 05:52:14,774 - main - INFO - 创建数据库表...
2025-04-05 05:52:14,976 - main - INFO - 数据库表创建完成
2025-04-05 05:52:14,977 - main - INFO - 注册路由...
2025-04-05 05:52:15,194 - main - INFO - 路由注册完成
2025-04-05 05:58:05,501 - main - INFO - 创建数据库表...
2025-04-05 05:58:05,706 - main - INFO - 数据库表创建完成
2025-04-05 05:58:05,706 - main - INFO - 注册路由...
2025-04-05 05:58:05,932 - main - INFO - 路由注册完成
2025-04-05 06:23:52,415 - main - INFO - 创建数据库表...
2025-04-05 06:23:52,616 - main - INFO - 数据库表创建完成
2025-04-05 06:23:52,616 - main - INFO - 注册路由...
2025-04-05 06:23:52,865 - main - INFO - 路由注册完成
2025-04-05 06:57:31,834 - main - INFO - 创建数据库表...
2025-04-05 06:57:32,043 - main - INFO - 数据库表创建完成
2025-04-05 06:57:32,044 - main - INFO - 注册路由...
2025-04-05 06:57:32,266 - main - INFO - 路由注册完成
2025-04-05 07:12:47,282 - main - INFO - 创建数据库表...
2025-04-05 07:12:47,488 - main - INFO - 数据库表创建完成
2025-04-05 07:12:47,488 - main - INFO - 注册路由...
2025-04-05 07:12:47,728 - main - INFO - 路由注册完成
2025-04-05 07:17:32,652 - main - INFO - 创建数据库表...
2025-04-05 07:17:32,841 - main - INFO - 数据库表创建完成
2025-04-05 07:17:32,842 - main - INFO - 注册路由...
2025-04-05 07:17:33,065 - main - INFO - 路由注册完成
2025-04-05 07:25:45,603 - main - INFO - 创建数据库表...
2025-04-05 07:25:45,802 - main - INFO - 数据库表创建完成
2025-04-05 07:25:45,803 - main - INFO - 注册路由...
2025-04-05 07:25:46,047 - main - INFO - 路由注册完成
2025-04-05 07:26:23,418 - admin_api - INFO - 访问登录页面: http://8.133.194.133:8000/admin/login
2025-04-05 07:40:09,572 - admin_api - INFO - 访问登录页面: http://8.133.194.133:8000/admin/
2025-04-05 07:41:04,901 - admin_api - INFO - 访问登录页面: http://8.133.194.133:8000/admin/
2025-04-05 07:49:57,649 - main - INFO - 创建数据库表...
2025-04-05 07:49:57,862 - main - INFO - 数据库表创建完成
2025-04-05 07:49:57,862 - main - INFO - 注册路由...
2025-04-05 07:49:58,092 - main - INFO - 路由注册完成
2025-04-05 07:50:53,844 - admin_api - INFO - 访问登录页面: http://8.133.194.133:8000/mlsp/admin/login
2025-04-05 07:51:32,132 - admin_api - INFO - 登录处理: http://8.133.194.133:8000/mlsp/admin/login
2025-04-05 07:51:32,132 - admin_api - INFO - 基础URL: http://8.133.194.133:8000/mlsp/
2025-04-05 07:51:32,132 - admin_api - INFO - 登录成功，重定向到dashboard
2025-04-05 07:51:32,132 - admin_api - INFO - 重定向URL: /admin/dashboard
2025-04-05 07:56:41,519 - inventory_api - INFO - 获取货架 1 的所有货位
2025-04-05 07:56:41,524 - inventory_api - INFO - 找到 4 个货位
2025-04-05 08:17:26,388 - employee_api - INFO - 标记订单 1 的商品 1 为已取货，库存ID: 1, 数量: 5
2025-04-05 08:17:26,403 - employee_api - INFO - 成功标记订单 1 的商品 1 为已取货
2025-04-05 08:18:34,557 - employee_api - INFO - 标记订单 1 为已完成
2025-04-05 08:18:34,559 - employee_api - ERROR - 订单 1 未上传照片，无法完成
2025-04-05 08:19:53,498 - employee_api - INFO - 标记订单 1 为已完成
2025-04-05 08:19:53,499 - employee_api - ERROR - 订单 1 未上传照片，无法完成
2025-04-05 08:20:05,744 - employee_api - INFO - 标记订单 1 为已完成
2025-04-05 08:20:05,745 - employee_api - ERROR - 订单 1 未上传照片，无法完成
2025-04-05 08:24:12,178 - main - INFO - 创建数据库表...
2025-04-05 08:24:12,377 - main - INFO - 数据库表创建完成
2025-04-05 08:24:12,377 - main - INFO - 注册路由...
2025-04-05 08:24:12,594 - main - INFO - 路由注册完成
2025-04-05 09:02:45,622 - main - INFO - 创建数据库表...
2025-04-05 09:02:45,840 - main - INFO - 数据库表创建完成
2025-04-05 09:02:45,840 - main - INFO - 注册路由...
2025-04-05 09:02:46,076 - main - INFO - 路由注册完成
2025-04-05 09:03:18,691 - employee_api - INFO - 上传订单 1 的照片
2025-04-05 09:03:18,702 - employee_api - INFO - 订单 1 照片上传成功，URL: /static/uploads/order_photos/order_1_20250405090318.jpg
2025-04-05 09:03:21,561 - employee_api - INFO - 标记订单 1 为已完成
2025-04-05 09:03:21,572 - employee_api - INFO - 订单 1 已标记为完成
2025-04-05 09:03:29,231 - admin_api - INFO - 访问登录页面: http://ritmohub.cn/admin/login
2025-04-05 09:03:38,285 - admin_api - INFO - 登录处理: http://ritmohub.cn/admin/login
2025-04-05 09:03:38,285 - admin_api - INFO - 基础URL: http://ritmohub.cn/mlsp/
2025-04-05 09:03:38,285 - admin_api - INFO - 登录失败，用户名或密码错误
2025-04-05 09:03:49,568 - admin_api - INFO - 登录处理: http://ritmohub.cn/admin/login
2025-04-05 09:03:49,568 - admin_api - INFO - 基础URL: http://ritmohub.cn/mlsp/
2025-04-05 09:03:49,568 - admin_api - INFO - 登录失败，用户名或密码错误
2025-04-05 09:04:07,739 - admin_api - INFO - 访问登录页面: http://ritmohub.cn/admin/login
2025-04-05 09:04:13,249 - admin_api - INFO - 登录处理: http://ritmohub.cn/admin/login
2025-04-05 09:04:13,250 - admin_api - INFO - 基础URL: http://ritmohub.cn/mlsp/
2025-04-05 09:04:13,250 - admin_api - INFO - 登录失败，用户名或密码错误
2025-04-05 09:04:26,553 - admin_api - INFO - 登录处理: http://ritmohub.cn/admin/login
2025-04-05 09:04:26,553 - admin_api - INFO - 基础URL: http://ritmohub.cn/mlsp/
2025-04-05 09:04:26,553 - admin_api - INFO - 登录失败，用户名或密码错误
2025-04-05 09:04:33,548 - admin_api - INFO - 登录处理: http://ritmohub.cn/admin/login
2025-04-05 09:04:33,548 - admin_api - INFO - 基础URL: http://ritmohub.cn/mlsp/
2025-04-05 09:04:33,548 - admin_api - INFO - 登录失败，用户名或密码错误
2025-04-05 09:04:48,711 - admin_api - INFO - 登录处理: http://ritmohub.cn/admin/login
2025-04-05 09:04:48,711 - admin_api - INFO - 基础URL: http://ritmohub.cn/mlsp/
2025-04-05 09:04:48,711 - admin_api - INFO - 登录失败，用户名或密码错误
2025-04-05 09:08:03,824 - admin_api - INFO - 访问登录页面: http://ritmohub.cn/admin/
2025-04-05 09:09:01,826 - admin_api - INFO - 登录处理: http://ritmohub.cn/admin/login
2025-04-05 09:09:01,826 - admin_api - INFO - 基础URL: http://ritmohub.cn/mlsp/
2025-04-05 09:09:01,826 - admin_api - INFO - 登录成功，重定向到dashboard
2025-04-05 09:09:01,826 - admin_api - INFO - 重定向URL: /admin/dashboard
2025-04-05 09:17:00,756 - main - INFO - 创建数据库表...
2025-04-05 09:17:00,949 - main - INFO - 数据库表创建完成
2025-04-05 09:17:00,949 - main - INFO - 注册路由...
2025-04-05 09:17:01,175 - main - INFO - 路由注册完成
2025-04-05 09:17:39,280 - employee_api - INFO - 标记订单 1 为已完成
2025-04-05 09:17:39,283 - employee_api - INFO - 订单 1 已标记为完成
2025-04-05 09:17:57,572 - employee_api - INFO - 标记订单 1 为已完成
2025-04-05 09:17:57,574 - employee_api - INFO - 订单 1 已标记为完成
2025-04-05 09:23:44,674 - main - INFO - 创建数据库表...
2025-04-05 09:23:44,877 - main - INFO - 数据库表创建完成
2025-04-05 09:23:44,878 - main - INFO - 注册路由...
2025-04-05 09:23:45,108 - main - INFO - 路由注册完成
2025-04-05 09:28:15,669 - main - ERROR - URL: http://ritmohub.cn/client/create-order, Method: POST, Error: invalid literal for int() with base 10: 'undefined', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/client.py", line 348, in client_submit_order
    product_id = int(product_id)
ValueError: invalid literal for int() with base 10: 'undefined'

2025-04-05 09:28:27,816 - main - ERROR - URL: http://ritmohub.cn/client/create-order, Method: POST, Error: invalid literal for int() with base 10: 'undefined', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/client.py", line 348, in client_submit_order
    product_id = int(product_id)
ValueError: invalid literal for int() with base 10: 'undefined'

2025-04-05 09:40:22,167 - main - INFO - 创建数据库表...
2025-04-05 09:40:22,369 - main - INFO - 数据库表创建完成
2025-04-05 09:40:22,369 - main - INFO - 注册路由...
2025-04-05 09:40:22,589 - main - INFO - 路由注册完成
2025-04-05 09:43:46,944 - admin_api - INFO - 访问登录页面: http://ritmohub.cn/admin/
2025-04-05 09:43:53,489 - admin_api - INFO - 登录处理: http://ritmohub.cn/admin/login
2025-04-05 09:43:53,489 - admin_api - INFO - 基础URL: http://ritmohub.cn/mlsp/
2025-04-05 09:43:53,489 - admin_api - INFO - 登录失败，用户名或密码错误
2025-04-05 09:45:33,038 - main - ERROR - URL: http://ritmohub.cn/admin/product/1/edit, Method: POST, Error: [Errno 2] No such file or directory: '/home/mlsp/app/mlsp/static/uploads/products/下载.jpg', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/admin.py", line 426, in admin_edit_product_post
    with open(file_location, "wb") as buffer:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mlsp/app/mlsp/static/uploads/products/下载.jpg'

2025-04-05 09:49:51,121 - main - INFO - 创建数据库表...
2025-04-05 09:49:51,315 - main - INFO - 数据库表创建完成
2025-04-05 09:49:51,315 - main - INFO - 注册路由...
2025-04-05 09:49:51,534 - main - INFO - 路由注册完成
2025-04-05 10:01:52,308 - main - INFO - 创建数据库表...
2025-04-05 10:01:52,505 - main - INFO - 数据库表创建完成
2025-04-05 10:01:52,505 - main - INFO - 注册路由...
2025-04-05 10:01:52,726 - main - INFO - 路由注册完成
2025-04-05 10:10:29,487 - main - INFO - 创建数据库表...
2025-04-05 10:10:29,718 - main - INFO - 数据库表创建完成
2025-04-05 10:10:29,719 - main - INFO - 注册路由...
2025-04-05 10:10:29,978 - main - INFO - 路由注册完成
2025-04-05 10:26:51,411 - main - INFO - 创建数据库表...
2025-04-05 10:26:51,630 - main - INFO - 数据库表创建完成
2025-04-05 10:26:51,631 - main - INFO - 注册路由...
2025-04-05 10:34:27,174 - main - INFO - 创建数据库表...
2025-04-05 10:34:27,372 - main - INFO - 数据库表创建完成
2025-04-05 10:34:27,373 - main - INFO - 注册路由...
2025-04-05 10:40:32,353 - main - INFO - 创建数据库表...
2025-04-05 10:40:32,568 - main - INFO - 数据库表创建完成
2025-04-05 10:40:32,568 - main - INFO - 注册路由...
2025-04-05 10:40:32,819 - main - INFO - 路由注册完成
2025-04-05 10:55:23,894 - main - INFO - 创建数据库表...
2025-04-05 10:55:24,090 - main - INFO - 数据库表创建完成
2025-04-05 10:55:24,090 - main - INFO - 注册路由...
2025-04-05 10:55:24,308 - main - INFO - 路由注册完成
2025-04-05 11:02:07,835 - main - INFO - 创建数据库表...
2025-04-05 11:02:08,046 - main - INFO - 数据库表创建完成
2025-04-05 11:02:08,046 - main - INFO - 注册路由...
2025-04-05 11:02:08,266 - main - INFO - 路由注册完成
2025-04-05 11:02:51,900 - main - ERROR - URL: http://ritmohub.cn/mlsp/client/create-order, Method: POST, Error: invalid literal for int() with base 10: 'undefined', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/client.py", line 347, in client_submit_order
    product_id = int(product_id)
ValueError: invalid literal for int() with base 10: 'undefined'

2025-04-05 11:16:59,535 - main - ERROR - URL: http://ritmohub.cn/mlsp/client/create-order, Method: POST, Error: invalid literal for int() with base 10: 'undefined', Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mlsp/app/api/endpoints/client.py", line 347, in client_submit_order
    product_id = int(product_id)
ValueError: invalid literal for int() with base 10: 'undefined'

2025-04-05 11:28:47,706 - main - INFO - 创建数据库表...
2025-04-05 11:28:47,923 - main - INFO - 数据库表创建完成
2025-04-05 11:28:47,923 - main - INFO - 注册路由...
2025-04-05 11:28:48,154 - main - INFO - 路由注册完成
